# Generated by Django 5.1.1 on 2024-10-24 12:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('audio_file', models.FileField(upload_to='tracks')),
                ('duration', models.DurationField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('preview_url', models.URLField(blank=True, null=True)),
                ('spotify_id', models.CharField(blank=True, max_length=255, null=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='albums.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='artists.artist')),
            ],
        ),
    ]
