# Generated by Django 5.1.1 on 2024-10-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='audio_file',
        ),
        migrations.AddField(
            model_name='track',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='tracks/'),
        ),
    ]
