services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  server:
    build:
      context: ./backend/yandex_music
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app # Привязка текущей папки backend к контейнеру
    environment:
      - DEBUG=1 # Можно задать дополнительные переменные окружения
      # depends_on:
      # - db

      # db:
      #   image: postgres:latest
      #   environment:
      #     POSTGRES_DB: your_db_name
      #     POSTGRES_USER: your_db_user
      #     POSTGRES_PASSWORD: your_db_password
      #   ports:
      #     - "5432:5432"
